import requests
from bs4 import BeautifulSoup


def fetch_walmartV2(query):

    cookies = {
        'wm_route_based_language': 'en-CA',
        'WM_SEC.AUTH_TOKEN': 'MTAyOTYyMDE4bu44p1Nih99bK4bqBaishxJA3ytsBAM5Q0nwbFiGH8AxayzRExtQKRX%2FjUTKbXB%2BRQkJHD8T9xerUw9OO2d6uCIEIOS15fQp1yBOBcSySWy%2FstRaF0GAVwOBenAu%2BHFIj8OFN4dileb20bpDLeCIlSFd%2FHsc7bnSe4%2BTLU2zbj2d2m%2B%2FFS1QjM92Pz6soYMF%2FYHmr6LRZ%2F2lOX2OJBv3JQxLx0%2FEY1jUeveU6jDHjhDb%2FSoGFgAYL9DGZ8K45WCXJ0tmvH1FCaN9tZDh4SCrHeyiXy51xK3A8%2Fr0NoetGyfikx%2Fg%2BdGP79eTUj0bzBqnN8F9OSHEEj8kBaByqFicyji%2F0mwGbpZuQERu6DdMsdFAZCruXYE61iLsm0eAVCTMy58CdMEqDoTAH89tto3LuUr1eX9YGQ0laieVMoEr348%3D',
        'auth': 'MTAyOTYyMDE4bu44p1Nih99bK4bqBaishxJA3ytsBAM5Q0nwbFiGH8AxayzRExtQKRX%2FjUTKbXB%2BRQkJHD8T9xerUw9OO2d6uCIEIOS15fQp1yBOBcSySWy%2FstRaF0GAVwOBenAu%2BHFIj8OFN4dileb20bpDLeCIlSFd%2FHsc7bnSe4%2BTLU2zbj2d2m%2B%2FFS1QjM92Pz6soYMF%2FYHmr6LRZ%2F2lOX2OJBv3JQxLx0%2FEY1jUeveU6jDHjhDb%2FSoGFgAYL9DGZ8K45WCXJ0tmvH1FCaN9tZDh4SCrHeyiXy51xK3A8%2Fr0NoetGyfikx%2Fg%2BdGP79eTUj0bzBqnN8F9OSHEEj8kBaByqFicyji%2F0mwGbpZuQERu6DdMsdFAZCruXYE61iLsm0eAVCTMy58CdMEqDoTAH89tto3LuUr1eX9YGQ0laieVMoEr348%3D',
        'DYN_USER_ID': '16cf0c18-aa94-49d2-97ba-b9352291cb15',
        'LT': '1705878443375',
        'WM.USER_STATE': 'GUEST%7CGuest',
        'type': 'GUEST%7CGuest',
        'ACID': '16cf0c18-aa94-49d2-97ba-b9352291cb15',
        'locDataV3': 'eyJwaWNrdXBTdG9yZSI6eyJhZGRyZXNzTGluZU9uZSI6IjkyNSBNYXJpbmUgRHIiLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic3RhdGVPclByb3ZpbmNlQ29kZSI6IkJDIiwiY291bnRyeUNvZGUiOiJDQSIsInBvc3RhbENvZGUiOiJWN1AgMVMyIiwic3RvcmVJZCI6IjMwNTciLCJkaXNwbGF5TmFtZSI6Ik4gVkFOQ09VVkVSLCBCLiBDLiIsImdlb1BvaW50Ijp7ImxhdGl0dWRlIjo0OS4zMjI2MDIsImxvbmdpdHVkZSI6LTEyMy4wOTg2MTV9LCJhY2Nlc3NQb2ludElkIjoiYmZkNjNhNjAtNzkwZi00NGQwLWFhYzItZTQxZWE4OTA5YmJjIiwiZnVsZmlsbG1lbnRTdG9yZUlkIjoiMzA1NyIsInByaWNpbmdTdG9yZUlkIjoiMzA1NyIsImZ1bGZpbGxtZW50T3B0aW9uIjoiUElDS1VQIiwiZnVsZmlsbG1lbnRUeXBlIjoiSU5TVE9SRV9QSUNLVVAifSwic2hpcHBpbmciOnsicG9zdGFsQ29kZSI6IlY3UCAxUzIiLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic3RhdGVPclByb3ZpbmNlQ29kZSI6IkJDIiwiY291bnRyeUNvZGUiOiJDQSIsImxhdGl0dWRlIjo0OS4zMjI2MDIsImxvbmdpdHVkZSI6LTEyMy4wOTg2MTUsImlzR2lmdEFkZHJlc3MiOmZhbHNlfSwiaW50ZW50IjoiUElDS1VQIiwiaXNFeHBsaWNpdEludGVudCI6ZmFsc2UsInZhbGlkYXRlS2V5IjoicHJvZDp2MjoxNmNmMGMxOC1hYTk0LTQ5ZDItOTdiYS1iOTM1MjI5MWNiMTUifQ%3D%3D',
        'hasLocData': '1',
        'userAppVersion': 'main-1.73.2-cd7a780-0119T0720',
        'vtc': 'aC0lgYbzlA4rGlC1yENJTk',
        'bstc': 'aC0lgYbzlA4rGlC1yENJTk',
        'xpa': '0yfou|9aQP5|U9fzx|Ux1PN|ZqI6v|oh-yO',
        'exp-ck': '0yfou19aQP51U9fzx1ZqI6veoh-yO1',
        'locale_ab': 'true',
        'ca-glass-web': 'true',
        'walmart.nearestLatLng': '"49.2624,-123.1604"',
        'userSegment': '40-percent',
        'ak_bmsc': 'DC3AAFF2B5A1156E3E5CE05F18928FDC~000000000000000000000000000000~YAAQLwIkF+lQXRGNAQAA81pHLhaR5I1RNejCrvRpCie55QWffxqdaEPF+cGlnbVIlfO/OTI82csmDqHN0D7Z/nVgUaezbpZvhEKTxv68q6pJ7hkNrnyC1Ow51K9IUF/T05hm+CVdBpYVP78sLEg9XXQewBBWpWUuNuZ7dm8fsqVdnA7Wbnlbk+Px1TEVkIhjJEUXFym7bsqCWEFZ6OfqO3cFER/tGsYlNPEHNErEP6zBPlHdFkdyghmqUIW7JCcIFJnMb3beGXM3mc/MDvuIQUfwubVFU+cc2HjrDSyuKzIwrsCjPUF6vvp6OAjHWEUYuY4yV9Cy/R/MPfZDBC36/fZvL1/eOe0IfY5KRwetjlbshz9OciTL+WeTLhKo4usVNyXIdClVLyLu6U0=',
        '_astc': '1dc9a3b99da3e73d3f4c26cd0543c916',
        'dimensionData': '791',
        'pxcts': 'd7379b41-b8b1-11ee-a79b-5a8d59a751aa',
        '_pxvid': 'd7378c3f-b8b1-11ee-a79b-36e294c6c117',
        'cartId': '3b5f4b3e-90d7-4f74-ad9e-cf0dc7ac85ba',
        'xpm': '1%2B1705878443%2BaC0lgYbzlA4rGlC1yENJTk~%2B0',
        '_gcl_au': '1.1.1522968395.1705878447',
        '_gid': 'GA1.2.672588417.1705878448',
        'criteo_thirdpartyuserid': 'YhhVdlHkAXewmSyrccw37k5XUpDjwTGc',
        'localStoreInfo': 'eyJwb3N0YWxDb2RlIjoiVjdQMVMyIiwibG9jYWxTdG9yZUlkIjoiMzA1NyIsInNlbGVjdGVkU3RvcmVJZCI6IjMwNTciLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic2VsZWN0ZWRTdG9yZU5hbWUiOiJOIFZBTkNPVVZFUiwgQi4gQy4iLCJmdWxmaWxsbWVudFN0b3JlSWQiOiIxMTA0IiwiZnVsZmlsbG1lbnRUeXBlIjoiREVMSVZFUlkifQo=',
        'deliveryCatchment': '1104',
        'walmart.nearestPostalCode': 'V7P1S2',
        'walmart.shippingPostalCode': 'V7P1S2',
        'defaultNearestStoreId': '3057',
        'ENV': 'ak-scus-t1-prod',
        'wmt.c': '0',
        'QuantumMetricSessionID': '470fc8ec94e1814bbe61525b0da3b9f7',
        'QuantumMetricUserID': '7232c9c96670a4cb25b1ed33fae4bcd2',
        'adblocked': 'true',
        '_ga_N1HN887KY7': 'GS1.1.1705878447.1.1.1705878468.39.0.0',
        '_ga': 'GA1.1.1649524327.1705878447',
        '_px3': 'db5fbc7e3f0f3002bfc738845ec3169cb063ef7b3daf432df3c5c71c28dc033a:OhBBMhL0E1CrzObpd/4iK5qRbjPV1/VZhshk699qjqSDOPb+9LFPVjCgDFJzM09n7VmWx/QdYLzXQuMIAShhdg==:1000:RgybDCmRoW7s+d10i0w07Rmo3OXf/HV9SLZYnUwDuBOr2lWV5RYhvyH3ZcXoJ/vrbwOsQoN70F0ucqccHyG+9NKA7TvNkeGR0wL2fk4pQeRSZcr5ol0R5DO+tZSj8GaRxzkoUAhHjWpBvTH7F8ZS/tat/1gX7GEg8Q4JLBzgQ7XwtwkakOdNZPgNr21SB5O20MrSuMMFd+29pTWZFLsSQozvQhbIkfMH+C7sj/htWro=',
        '_ga_D2P3FM55BM': 'GS1.1.1705878447.1.1.1705878488.0.0.0',
        'seqnum': '9',
        'TS010110a1': '01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db',
        'TS01ea8d4c': '01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db',
        'TS0180da25': '01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db',
        'TSe62c5f0d027': '086ffbdc03ab20008bd67f5b1b70543930610a66885e9c81869efeed0de3226c921b4cfdd44e55eb08d3d77a921130008c1ddf984ef82fc6ff74ee5428ccdfad8d9451ff13b261195764676ebb698f4b1a28754ac9184b33ace234990adc1023',
        'bm_sv': 'FCBC68736C460D024892B57C86AF2661~YAAQLwIkF9haXRGNAQAADgZILhYpAvbCML/wVtuTZQM2AAA9QVlBRX9aKaxuIi+L5adfOKMDEP43AwMmu53+auJ7TsmTgNbngQk6461ADFFdU4xROCyN/ri8f/gsDSNi6Ny6mqelHS3/qknWFaYNNLbS3VavBCyCic2dkYZPY0z0JZbCjq8gdhww8u1b59kCBx23TUPppvBGPXVz86/X8Eu+43ySu2dFO/5/OfZLXSmlWtrTmYxGnSc37xMAcOwATQ==~1',
        '_pxde': '9e85f5e31ea363528386088d4e7672e01047ba6f6b68a2aa97123060cd0cae1b:eyJ0aW1lc3RhbXAiOjE3MDU4Nzg1NDg2MDZ9',
        'uxcon': 'enforce=false&p13n=true&ads=true&createdAt=1705878444754&modifiedAt=1705878601304',
    }

    headers = {
        'authority': 'www.walmart.ca',
        'accept': 'application/json',
        'accept-language': 'en-CA',
        'content-type': 'application/json',
        # 'cookie': 'wm_route_based_language=en-CA; WM_SEC.AUTH_TOKEN=MTAyOTYyMDE4bu44p1Nih99bK4bqBaishxJA3ytsBAM5Q0nwbFiGH8AxayzRExtQKRX%2FjUTKbXB%2BRQkJHD8T9xerUw9OO2d6uCIEIOS15fQp1yBOBcSySWy%2FstRaF0GAVwOBenAu%2BHFIj8OFN4dileb20bpDLeCIlSFd%2FHsc7bnSe4%2BTLU2zbj2d2m%2B%2FFS1QjM92Pz6soYMF%2FYHmr6LRZ%2F2lOX2OJBv3JQxLx0%2FEY1jUeveU6jDHjhDb%2FSoGFgAYL9DGZ8K45WCXJ0tmvH1FCaN9tZDh4SCrHeyiXy51xK3A8%2Fr0NoetGyfikx%2Fg%2BdGP79eTUj0bzBqnN8F9OSHEEj8kBaByqFicyji%2F0mwGbpZuQERu6DdMsdFAZCruXYE61iLsm0eAVCTMy58CdMEqDoTAH89tto3LuUr1eX9YGQ0laieVMoEr348%3D; auth=MTAyOTYyMDE4bu44p1Nih99bK4bqBaishxJA3ytsBAM5Q0nwbFiGH8AxayzRExtQKRX%2FjUTKbXB%2BRQkJHD8T9xerUw9OO2d6uCIEIOS15fQp1yBOBcSySWy%2FstRaF0GAVwOBenAu%2BHFIj8OFN4dileb20bpDLeCIlSFd%2FHsc7bnSe4%2BTLU2zbj2d2m%2B%2FFS1QjM92Pz6soYMF%2FYHmr6LRZ%2F2lOX2OJBv3JQxLx0%2FEY1jUeveU6jDHjhDb%2FSoGFgAYL9DGZ8K45WCXJ0tmvH1FCaN9tZDh4SCrHeyiXy51xK3A8%2Fr0NoetGyfikx%2Fg%2BdGP79eTUj0bzBqnN8F9OSHEEj8kBaByqFicyji%2F0mwGbpZuQERu6DdMsdFAZCruXYE61iLsm0eAVCTMy58CdMEqDoTAH89tto3LuUr1eX9YGQ0laieVMoEr348%3D; DYN_USER_ID=16cf0c18-aa94-49d2-97ba-b9352291cb15; LT=1705878443375; WM.USER_STATE=GUEST%7CGuest; type=GUEST%7CGuest; ACID=16cf0c18-aa94-49d2-97ba-b9352291cb15; locDataV3=eyJwaWNrdXBTdG9yZSI6eyJhZGRyZXNzTGluZU9uZSI6IjkyNSBNYXJpbmUgRHIiLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic3RhdGVPclByb3ZpbmNlQ29kZSI6IkJDIiwiY291bnRyeUNvZGUiOiJDQSIsInBvc3RhbENvZGUiOiJWN1AgMVMyIiwic3RvcmVJZCI6IjMwNTciLCJkaXNwbGF5TmFtZSI6Ik4gVkFOQ09VVkVSLCBCLiBDLiIsImdlb1BvaW50Ijp7ImxhdGl0dWRlIjo0OS4zMjI2MDIsImxvbmdpdHVkZSI6LTEyMy4wOTg2MTV9LCJhY2Nlc3NQb2ludElkIjoiYmZkNjNhNjAtNzkwZi00NGQwLWFhYzItZTQxZWE4OTA5YmJjIiwiZnVsZmlsbG1lbnRTdG9yZUlkIjoiMzA1NyIsInByaWNpbmdTdG9yZUlkIjoiMzA1NyIsImZ1bGZpbGxtZW50T3B0aW9uIjoiUElDS1VQIiwiZnVsZmlsbG1lbnRUeXBlIjoiSU5TVE9SRV9QSUNLVVAifSwic2hpcHBpbmciOnsicG9zdGFsQ29kZSI6IlY3UCAxUzIiLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic3RhdGVPclByb3ZpbmNlQ29kZSI6IkJDIiwiY291bnRyeUNvZGUiOiJDQSIsImxhdGl0dWRlIjo0OS4zMjI2MDIsImxvbmdpdHVkZSI6LTEyMy4wOTg2MTUsImlzR2lmdEFkZHJlc3MiOmZhbHNlfSwiaW50ZW50IjoiUElDS1VQIiwiaXNFeHBsaWNpdEludGVudCI6ZmFsc2UsInZhbGlkYXRlS2V5IjoicHJvZDp2MjoxNmNmMGMxOC1hYTk0LTQ5ZDItOTdiYS1iOTM1MjI5MWNiMTUifQ%3D%3D; hasLocData=1; userAppVersion=main-1.73.2-cd7a780-0119T0720; vtc=aC0lgYbzlA4rGlC1yENJTk; bstc=aC0lgYbzlA4rGlC1yENJTk; xpa=0yfou|9aQP5|U9fzx|Ux1PN|ZqI6v|oh-yO; exp-ck=0yfou19aQP51U9fzx1ZqI6veoh-yO1; locale_ab=true; ca-glass-web=true; walmart.nearestLatLng="49.2624,-123.1604"; userSegment=40-percent; ak_bmsc=DC3AAFF2B5A1156E3E5CE05F18928FDC~000000000000000000000000000000~YAAQLwIkF+lQXRGNAQAA81pHLhaR5I1RNejCrvRpCie55QWffxqdaEPF+cGlnbVIlfO/OTI82csmDqHN0D7Z/nVgUaezbpZvhEKTxv68q6pJ7hkNrnyC1Ow51K9IUF/T05hm+CVdBpYVP78sLEg9XXQewBBWpWUuNuZ7dm8fsqVdnA7Wbnlbk+Px1TEVkIhjJEUXFym7bsqCWEFZ6OfqO3cFER/tGsYlNPEHNErEP6zBPlHdFkdyghmqUIW7JCcIFJnMb3beGXM3mc/MDvuIQUfwubVFU+cc2HjrDSyuKzIwrsCjPUF6vvp6OAjHWEUYuY4yV9Cy/R/MPfZDBC36/fZvL1/eOe0IfY5KRwetjlbshz9OciTL+WeTLhKo4usVNyXIdClVLyLu6U0=; _astc=1dc9a3b99da3e73d3f4c26cd0543c916; dimensionData=791; pxcts=d7379b41-b8b1-11ee-a79b-5a8d59a751aa; _pxvid=d7378c3f-b8b1-11ee-a79b-36e294c6c117; cartId=3b5f4b3e-90d7-4f74-ad9e-cf0dc7ac85ba; xpm=1%2B1705878443%2BaC0lgYbzlA4rGlC1yENJTk~%2B0; _gcl_au=1.1.1522968395.1705878447; _gid=GA1.2.672588417.1705878448; criteo_thirdpartyuserid=YhhVdlHkAXewmSyrccw37k5XUpDjwTGc; localStoreInfo=eyJwb3N0YWxDb2RlIjoiVjdQMVMyIiwibG9jYWxTdG9yZUlkIjoiMzA1NyIsInNlbGVjdGVkU3RvcmVJZCI6IjMwNTciLCJjaXR5IjoiTm9ydGggVmFuY291dmVyIiwic2VsZWN0ZWRTdG9yZU5hbWUiOiJOIFZBTkNPVVZFUiwgQi4gQy4iLCJmdWxmaWxsbWVudFN0b3JlSWQiOiIxMTA0IiwiZnVsZmlsbG1lbnRUeXBlIjoiREVMSVZFUlkifQo=; deliveryCatchment=1104; walmart.nearestPostalCode=V7P1S2; walmart.shippingPostalCode=V7P1S2; defaultNearestStoreId=3057; ENV=ak-scus-t1-prod; wmt.c=0; QuantumMetricSessionID=470fc8ec94e1814bbe61525b0da3b9f7; QuantumMetricUserID=7232c9c96670a4cb25b1ed33fae4bcd2; adblocked=true; _ga_N1HN887KY7=GS1.1.1705878447.1.1.1705878468.39.0.0; _ga=GA1.1.1649524327.1705878447; _px3=db5fbc7e3f0f3002bfc738845ec3169cb063ef7b3daf432df3c5c71c28dc033a:OhBBMhL0E1CrzObpd/4iK5qRbjPV1/VZhshk699qjqSDOPb+9LFPVjCgDFJzM09n7VmWx/QdYLzXQuMIAShhdg==:1000:RgybDCmRoW7s+d10i0w07Rmo3OXf/HV9SLZYnUwDuBOr2lWV5RYhvyH3ZcXoJ/vrbwOsQoN70F0ucqccHyG+9NKA7TvNkeGR0wL2fk4pQeRSZcr5ol0R5DO+tZSj8GaRxzkoUAhHjWpBvTH7F8ZS/tat/1gX7GEg8Q4JLBzgQ7XwtwkakOdNZPgNr21SB5O20MrSuMMFd+29pTWZFLsSQozvQhbIkfMH+C7sj/htWro=; _ga_D2P3FM55BM=GS1.1.1705878447.1.1.1705878488.0.0.0; seqnum=9; TS010110a1=01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db; TS01ea8d4c=01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db; TS0180da25=01692ab7e39d38dee5b2a2a5a2a4b5f154232b6cd05a5e53af9ba1957c19d784f8fafb0c07357ba1442920744d334b747327ff48db; TSe62c5f0d027=086ffbdc03ab20008bd67f5b1b70543930610a66885e9c81869efeed0de3226c921b4cfdd44e55eb08d3d77a921130008c1ddf984ef82fc6ff74ee5428ccdfad8d9451ff13b261195764676ebb698f4b1a28754ac9184b33ace234990adc1023; bm_sv=FCBC68736C460D024892B57C86AF2661~YAAQLwIkF9haXRGNAQAADgZILhYpAvbCML/wVtuTZQM2AAA9QVlBRX9aKaxuIi+L5adfOKMDEP43AwMmu53+auJ7TsmTgNbngQk6461ADFFdU4xROCyN/ri8f/gsDSNi6Ny6mqelHS3/qknWFaYNNLbS3VavBCyCic2dkYZPY0z0JZbCjq8gdhww8u1b59kCBx23TUPppvBGPXVz86/X8Eu+43ySu2dFO/5/OfZLXSmlWtrTmYxGnSc37xMAcOwATQ==~1; _pxde=9e85f5e31ea363528386088d4e7672e01047ba6f6b68a2aa97123060cd0cae1b:eyJ0aW1lc3RhbXAiOjE3MDU4Nzg1NDg2MDZ9; uxcon=enforce=false&p13n=true&ads=true&createdAt=1705878444754&modifiedAt=1705878601304',
        'device_profile_ref_id': 'hM0bIO15kkcwtF6JDdRuDkpYDWDvaKMR8--F',
        'downlink': '10',
        'dpr': '1.25',
        'origin': 'https://www.walmart.ca',
        'referer': 'https://www.walmart.ca/en/search?q=banana',
        'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'traceparent': '00-56527cc80f9b497f941ec79b30116835-1c10c86212a38297-00',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'wm_mp': 'true',
        'wm_page_url': 'https://www.walmart.ca/en/search?q=banana',
        'wm_qos.correlation_id': 'yJ8jkHiqZQ4hii_v_6Y539lL5mJJErZoxfkc',
        'x-apollo-operation-name': 'Search',
        'x-enable-server-timing': '1',
        'x-latency-trace': '1',
        'x-o-bu': 'WALMART-CA',
        'x-o-ccm': 'server',
        'x-o-correlation-id': 'yJ8jkHiqZQ4hii_v_6Y539lL5mJJErZoxfkc',
        'x-o-gql-query': 'query Search',
        'x-o-mart': 'B2C',
        'x-o-platform': 'rweb',
        'x-o-platform-version': 'main-1.73.2-cd7a780-0119T0720',
        'x-o-segment': 'oaoh',
    }

    params = {
        'pap': 'undefined',
        'query': query,
        'page': '1',
        'prg': 'desktop',
        'sort': 'best_match',
        'ps': '40',
        'limit': '40',
        'additionalQueryParams.isMoreOptionsTileEnabled': 'true',
        'searchArgs.query': query,
        'searchArgs.prg': 'desktop',
        'fitmentFieldParams': 'true_true_false',
        'enableFashionTopNav': 'false',
        'enableRelatedSearches': 'false',
        'enablePortableFacets': 'true',
        'enableFacetCount': 'true',
        'fetchMarquee': 'true',
        'fetchSkyline': 'true',
        'fetchGallery': 'false',
        'fetchSbaTop': 'true',
        'fetchDac': 'false',
        'tenant': 'CA_GLASS',
        'enableFlattenedFitment': 'false',
        'enableMultiSave': 'true',
        'enableSellerType': 'true',
    }

    json_data = {
        'query': 'query Search( $query:String $limit:Int $page:Int $prg:Prg! $facet:String $sort:Sort = best_match $catId:String $max_price:String $min_price:String $spelling:Boolean = true $affinityOverride:AffinityOverride $storeSlotBooked:String $pap:String $ps:Int $ptss:String $recall_set:String $fitmentFieldParams:JSON ={}$fitmentSearchParams:JSON ={}$fetchMarquee:Boolean! $trsp:String $fetchSkyline:Boolean! $fetchGallery:Boolean! $fetchSbaTop:Boolean! $fetchDac:Boolean! $additionalQueryParams:JSON ={}$searchArgs:SearchArgumentsForCLS $enablePortableFacets:Boolean = false $enableFashionTopNav:Boolean = false $intentSource:IntentSource $tenant:String! $enableFacetCount:Boolean = true $pageType:String! = "SearchPage" $enableFlattenedFitment:Boolean = false $enableRelatedSearches:Boolean = false $enableMultiSave:Boolean = false $enableSellerType:Boolean = false ){search( query:$query limit:$limit page:$page prg:$prg pap:$pap facet:$facet sort:$sort cat_id:$catId max_price:$max_price min_price:$min_price spelling:$spelling affinityOverride:$affinityOverride storeSlotBooked:$storeSlotBooked ps:$ps ptss:$ptss recall_set:$recall_set trsp:$trsp intentSource:$intentSource additionalQueryParams:$additionalQueryParams pageType:$pageType ){query searchResult{...SearchResultFragment}}contentLayout( channel:"WWW" pageType:$pageType tenant:$tenant version:"v1" searchArgs:$searchArgs ){modules( p13n:{page:$page userReqInfo:{refererContext:{query:$query}}}){...ModuleFragment configs{__typename...on EnricherModuleConfigsV1{zoneV1}...SearchNonItemFragment...on TempoWM_GLASSWWWSponsoredProductCarouselConfigs{_rawConfigs}...on TempoWM_GLASSWWWEmailSignUpWidgetConfigs{_rawConfigs}...on _TempoWM_GLASSWWWSearchSortFilterModuleConfigs{facetsV1 @skip(if:$enablePortableFacets){...FacetFragment}topNavFacets @include(if:$enablePortableFacets){...FacetFragment}allSortAndFilterFacets @include(if:$enablePortableFacets){...FacetFragment}}...on _TempoWM_GLASSWWWSearchGuidedNavModuleConfigs{guidedNavigation{...GuidedNavFragment}}...on TempoWM_GLASSWWWBrowsingHistoryConfigs{...BrowsingHistoryFragment}...on TempoWM_GLASSWWWSearchACCStoreSelectionConfigs{ctaText userInfoMessage headingDetails{heading headingWhenFulfillmentIsSelectedAsPickup}}...on TempoWM_GLASSWWWPillsModuleConfigs{moduleSource pillsV2{...PillsModuleFragment}}...TileTakeOverProductFragment...on TempoWM_GLASSWWWSearchFitmentModuleConfigs{fitments( fitmentSearchParams:$fitmentSearchParams fitmentFieldParams:$fitmentFieldParams ){...FitmentFragment sisFitmentResponse{...SearchResultFragment}}}...on TempoWM_GLASSWWWStoreSelectionHeaderConfigs{fulfillmentMethodLabel storeDislayName}...on TempoWM_GLASSWWWBenefitProgramBannerPlaceholderConfigs{_rawConfigs}...FashionTopNavFragment @include(if:$enableFashionTopNav)...BrandAmplifierAdConfigs @include(if:$fetchSbaTop)...BannerModuleFragment...SearchNonProductBannerFragment...SearchSubscriptionBannerFragment...MarqueeDisplayAdConfigsFragment @include(if:$fetchMarquee)...SkylineDisplayAdConfigsFragment @include(if:$fetchSkyline)...GalleryDisplayAdConfigsFragment @include(if:$fetchGallery)...DynamicAdContainerConfigsFragment @include(if:$fetchDac)...HorizontalChipModuleConfigsFragment...SkinnyBannerFragment...SponsoredVideoAdFragment}}...LayoutFragment pageMetadata{location{pickupStore deliveryStore intent postalCode stateOrProvinceCode city storeId accessPointId accessType spokeNodeId}pageContext}}}fragment SearchResultFragment on SearchInterface{title aggregatedCount...BreadCrumbFragment...DebugFragment...ItemStacksFragment...SearchNonProductFragment...PageMetaDataFragment...PaginationFragment...SpellingFragment...SpanishTranslationFragment...RequestContextFragment...ErrorResponse...RelatedSearch @include(if:$enableRelatedSearches) modules{facetsV1 @skip(if:$enablePortableFacets){...FacetFragment}topNavFacets @include(if:$enablePortableFacets){...FacetFragment}allSortAndFilterFacets @include(if:$enablePortableFacets){...FacetFragment}guidedNavigation{...GuidedNavFragment}guidedNavigationV2{...PillsModuleFragment}pills{...PillsModuleFragment}spellCheck{title subTitle urlLinkText url}}pac{relevantPT{productType score}showPAC reasonCode}isModularSearch hasMorePages moduleArrayV2{meta{beacon displayType id subType type}content{bottomSeparator initialCount subtitle title data{__typename...ContentDataFragment...RelatedSearchesFragment}items{...ModularSearchItemFragment}}}}fragment RelatedSearchesFragment on RelatedSearchResults{imageUrl title url}fragment ContentDataFragment on ContentData{type name displayName url imageUrl}fragment ModularSearchItemFragment on Product{__typename buyBoxSuppression similarItems id usItemId wfsEnabled @include(if:$enableSellerType) fitmentLabel name checkStoreAvailabilityATC seeShippingEligibility brand type shortDescription weightIncrement topResult additionalOfferCount availabilityInNearbyStore imageInfo{...ModularSearchProductImageInfoFragment}aspectInfo{name header id snippet}canonicalUrl externalInfo{url}itemType category{path{name url}}badges{flags{__typename...on BaseBadge{key bundleId @include(if:$enableMultiSave) text type id styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{key text type}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType otherInfo{moqText}rank slaText styleId text type templates{regular faster unavailable}badgeContent{type value id}}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}classType averageRating numberOfReviews esrb mediaRating salesUnitType sellerId sellerName hasSellerBadge isEarlyAccessItem earlyAccessEvent annualEvent annualEventV2 availabilityStatusV2{display value}groupMetaData{groupType groupSubType numberOfComponents groupComponents{quantity offerId componentType productDisplayName}}productLocation{displayValue aisle{zone aisle}}fulfillmentSpeed offerId preOrder{...ModularSearchPreorderFragment}pac{showPAC reasonCode fulfillmentPacModule}fulfillmentSummary{storeId deliveryDate}priceInfo{...ModularSearchProductPriceInfoFragment}variantCriteria{...ModularSearchVariantCriteriaFragment}snapEligible fulfillmentTitle fulfillmentType brand manufacturerName showAtc sponsoredProduct{spQs clickBeacon spTags viewBeacon}showOptions showBuyNow quickShop quickShopCTALabel rewards{eligible state minQuantity rewardAmt promotionId selectionToken rewardMultiplierStr cbOffer term expiry description}promoDiscount{discount discountEligible discountEligibleVariantPresent promotionId promoOffer state}arExperiences{isARHome isZeekit isAROptical}eventAttributes{...ModularSearchProductEventAttributesFragment}subscription{subscriptionEligible}hasCarePlans petRx{eligible singleDispense}vision{ageGroup visionCenterApproved}showExploreOtherConditionsCTA isPreowned pglsCondition newConditionProductId preownedCondition keyAttributes{displayEnum value}}fragment ModularSearchProductImageInfoFragment on ProductImageInfo{id name thumbnailUrl size}fragment ModularSearchProductPriceInfoFragment on ProductPriceInfo{priceRange{minPrice maxPrice priceString}currentPrice{...ModularSearchProductPriceFragment priceDisplay}comparisonPrice{...ModularSearchProductPriceFragment}wasPrice{...ModularSearchProductPriceFragment}unitPrice{...ModularSearchProductPriceFragment}listPrice{...ModularSearchProductPriceFragment}savingsAmount{...ModularSearchProductSavingsFragment}shipPrice{...ModularSearchProductPriceFragment}subscriptionPrice{priceString subscriptionString}priceDisplayCodes{priceDisplayCondition finalCostByWeight submapType}wPlusEarlyAccessPrice{memberPrice{...ModularSearchProductPriceFragment}savings{...ModularSearchProductSavingsFragment}eventStartTime eventStartTimeDisplay}subscriptionDualPrice subscriptionPercentage}fragment ModularSearchPreorderFragment on PreOrder{isPreOrder preOrderMessage preOrderStreetDateMessage streetDate streetDateDisplayable streetDateType}fragment ModularSearchProductPriceFragment on ProductPrice{price priceString variantPriceString priceType currencyUnit priceDisplay}fragment ModularSearchProductSavingsFragment on ProductSavings{amount percent priceString}fragment ModularSearchProductEventAttributesFragment on EventAttributes{priceFlip specialBuy}fragment ModularSearchVariantCriteriaFragment on VariantCriterion{name type id displayName isVariantTypeSwatch variantList{id images name rank swatchImageUrl availabilityStatus products selectedProduct{canonicalUrl usItemId}}}fragment ModuleFragment on TempoModule{__typename type name version moduleId schedule{priority}matchedTrigger{zone}}fragment LayoutFragment on ContentLayout{layouts{id layout}}fragment BreadCrumbFragment on SearchInterface{breadCrumb{id name url cat_level}}fragment DebugFragment on SearchInterface{debug{sisUrl adsUrl presoDebugInformation{explainerToolsResponse}}}fragment ItemStacksFragment on SearchInterface{itemStacks{displayMessage meta{adsBeacon{adUuid moduleInfo max_ads}spBeaconInfo{adUuid moduleInfo pageViewUUID placement max}query isPartialResult stackId stackType stackName title subTitle titleKey queryUsedForSearchResults layoutEnum totalItemCount totalItemCountDisplay viewAllParams{query cat_id sort facet affinityOverride recall_set min_price max_price}borderColor iconUrl}itemsV2{...ItemFragment...InGridMarqueeAdFragment...InGridAdFragment...TileTakeOverTileFragment}content{title subtitle data{type name displayName url imageUrl}}}}fragment ItemFragment on Product{__typename buyBoxSuppression similarItems id usItemId wfsEnabled @include(if:$enableSellerType) fitmentLabel name checkStoreAvailabilityATC seeShippingEligibility brand type shortDescription weightIncrement topResult additionalOfferCount availabilityInNearbyStore imageInfo{...ProductImageInfoFragment}aspectInfo{name header id snippet}canonicalUrl externalInfo{url}itemType category{path{name url}}badges{flags{__typename...on BaseBadge{key bundleId @include(if:$enableMultiSave) text type id styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{key text type}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType otherInfo{moqText}rank slaText styleId text type templates{regular faster unavailable}badgeContent{type value id}}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}classType averageRating numberOfReviews esrb mediaRating salesUnitType sellerId sellerName hasSellerBadge isEarlyAccessItem earlyAccessEvent annualEvent annualEventV2 availabilityStatusV2{display value}groupMetaData{groupType groupSubType numberOfComponents groupComponents{quantity offerId componentType productDisplayName}}productLocation{displayValue aisle{zone aisle}}fulfillmentSpeed offerId preOrder{...PreorderFragment}pac{showPAC reasonCode fulfillmentPacModule}fulfillmentSummary{storeId deliveryDate}priceInfo{...ProductPriceInfoFragment}variantCriteria{...VariantCriteriaFragment}snapEligible fulfillmentTitle fulfillmentType brand manufacturerName showAtc sponsoredProduct{spQs clickBeacon spTags viewBeacon}showOptions showBuyNow quickShop quickShopCTALabel rewards{eligible state minQuantity rewardAmt promotionId selectionToken rewardMultiplierStr cbOffer term expiry description}promoDiscount{discount discountEligible discountEligibleVariantPresent promotionId promoOffer state}arExperiences{isARHome isZeekit isAROptical}eventAttributes{...ProductEventAttributesFragment}subscription{subscriptionEligible}hasCarePlans petRx{eligible singleDispense}vision{ageGroup visionCenterApproved}showExploreOtherConditionsCTA isPreowned pglsCondition newConditionProductId preownedCondition keyAttributes{displayEnum value}}fragment ProductImageInfoFragment on ProductImageInfo{id name thumbnailUrl size}fragment ProductPriceInfoFragment on ProductPriceInfo{priceRange{minPrice maxPrice priceString}currentPrice{...ProductPriceFragment priceDisplay}comparisonPrice{...ProductPriceFragment}wasPrice{...ProductPriceFragment}unitPrice{...ProductPriceFragment}listPrice{...ProductPriceFragment}savingsAmount{...ProductSavingsFragment}shipPrice{...ProductPriceFragment}subscriptionPrice{priceString subscriptionString}priceDisplayCodes{priceDisplayCondition finalCostByWeight submapType}wPlusEarlyAccessPrice{memberPrice{...ProductPriceFragment}savings{...ProductSavingsFragment}eventStartTime eventStartTimeDisplay}subscriptionDualPrice subscriptionPercentage}fragment PreorderFragment on PreOrder{isPreOrder preOrderMessage preOrderStreetDateMessage streetDate streetDateDisplayable streetDateType}fragment ProductPriceFragment on ProductPrice{price priceString variantPriceString priceType currencyUnit priceDisplay}fragment ProductSavingsFragment on ProductSavings{amount percent priceString}fragment ProductEventAttributesFragment on EventAttributes{priceFlip specialBuy}fragment VariantCriteriaFragment on VariantCriterion{name type id displayName isVariantTypeSwatch variantList{id images name rank swatchImageUrl availabilityStatus products selectedProduct{canonicalUrl usItemId}}}fragment InGridMarqueeAdFragment on MarqueePlaceholder{__typename type moduleLocation lazy}fragment InGridAdFragment on AdPlaceholder{__typename type moduleLocation lazy adUuid hasVideo moduleInfo}fragment TileTakeOverTileFragment on TileTakeOverProductPlaceholder{__typename type tileTakeOverTile{span title subtitle image{src alt assetId assetName}logoImage{src alt}backgroundColor titleTextColor subtitleTextColor tileCta{ctaLink{clickThrough{value}linkText title}ctaType ctaTextColor}adsEnabled adCardLocation enableLazyLoad}}fragment SearchNonProductFragment on SearchInterface{nonProduct{title image imageAlt displayName description url urlAlt}}fragment PageMetaDataFragment on SearchInterface{pageMetadata{storeSelectionHeader{fulfillmentMethodLabel storeDislayName}title canonical description location{addressId}subscriptionEligible}}fragment PaginationFragment on SearchInterface{paginationV2{maxPage pageProperties}}fragment SpanishTranslationFragment on SearchInterface{translation{metadata{originalQuery translatedQuery isTranslated translationOfferType moduleSource}translationModule{title urlLinkText originalQueryUrl}}}fragment SpellingFragment on SearchInterface{spelling{correctedTerm}}fragment RequestContextFragment on SearchInterface{requestContext{vertical hasGicIntent isFitmentFilterQueryApplied searchMatchType categories{id name}}}fragment ErrorResponse on SearchInterface{errorResponse{correlationId source errorCodes errors{errorType statusCode statusMsg source}}}fragment GuidedNavFragment on GuidedNavigationSearchInterface{title url}fragment PillsModuleFragment on PillsSearchInterface{title titleColor url image:imageV1{src alt assetId assetName}}fragment BrowsingHistoryFragment on TempoWM_GLASSWWWBrowsingHistoryConfigs{title products{id usItemId imageInfo{thumbnailUrl}classType canonicalUrl name}}fragment BannerViewConfigFragment on BannerViewConfigCLS{title image imageAlt displayName description url urlAlt appStoreLink appStoreLinkAlt playStoreLink playStoreLinkAlt}fragment BannerModuleFragment on TempoWM_GLASSWWWSearchBannerConfigs{moduleType viewConfig{...BannerViewConfigFragment}}fragment SearchNonProductBannerFragment on TempoWM_GLASSWWWSearchNonProductBannerConfigs{nps{query normalisedQuery nonProduct{title image imageAlt displayName description url urlAlt}}viewConfig{...BannerViewConfigFragment}}fragment SearchSubscriptionBannerFragment on TempoWM_GLASSWWWSearchSubscriptionBannerConfigs{viewConfig{...BannerViewConfigFragment}}fragment FacetFragment on Facet{title name expandOnLoad type displayType layout min max selectedMin selectedMax unboundedMax stepSize isSelected values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL}}}}}}}}}fragment FitmentFragment on Fitments{partTypeIDs fitmentType isNarrowSearch fitmentOptionalFields{...FitmentFieldFragment}result{fitmentType status formId position quantityTitle extendedAttributes{...FitmentFieldFragment}labels{...LabelFragment}resultSubTitle notes suggestions{...FitmentSuggestionFragment}}redirectUrl{title clickThrough{value}}labels{...LabelFragment}savedVehicle{vehicleType{...VehicleFieldFragment}vehicleYear{...VehicleFieldFragment}vehicleMake{...VehicleFieldFragment}vehicleModel{...VehicleFieldFragment}additionalAttributes{...VehicleFieldFragment}}fitmentFields{...VehicleFieldFragment}fitmentForms{id fields{...FitmentFieldFragment}title labels{...LabelFragment}garage{vehicles{...AutoVehicle}}}}fragment LabelFragment on FitmentLabels{ctas{...FitmentLabelEntityFragment}messages{...FitmentLabelEntityFragment}links{...FitmentLabelEntityFragment}images{...FitmentLabelEntityFragment}}fragment FitmentLabelEntityFragment on FitmentLabelEntity{id label labelV1 @include(if:$enableFlattenedFitment)}fragment VehicleFieldFragment on FitmentVehicleField{id label value}fragment FitmentFieldFragment on FitmentField{id displayName value extended data{value label}dependsOn isRequired errorMessage}fragment FitmentSuggestionFragment on FitmentSuggestion{id position loadIndex speedRating searchQueryParam labels{...LabelFragment}cat_id fitmentSuggestionParams{id value}optionalSuggestionParams{id value displayName data{label value}dependsOn isRequired errorMessage}applicationSuggestionParams{position}}fragment MarqueeDisplayAdConfigsFragment on TempoWM_GLASSWWWMarqueeDisplayAdConfigs{_rawConfigs ad{...DisplayAdFragment}}fragment DisplayAdFragment on Ad{...AdFragment adContent{type data{__typename...AdDataDisplayAdFragment}}}fragment AdFragment on Ad{status moduleType platform pageId pageType storeId stateCode zipCode pageContext moduleConfigs adsContext adRequestComposite}fragment AdDataDisplayAdFragment on AdData{...on DisplayAd{json status}}fragment GalleryDisplayAdConfigsFragment on TempoWM_GLASSWWWGalleryDisplayAdConfigs{_rawConfigs}fragment SkylineDisplayAdConfigsFragment on TempoWM_GLASSWWWSkylineDisplayAdConfigs{_rawConfigs ad{...SkylineDisplayAdFragment}}fragment SkylineDisplayAdFragment on Ad{...SkylineAdFragment adContent{type data{__typename...SkylineAdDataDisplayAdFragment}}}fragment SkylineAdFragment on Ad{status moduleType platform pageId pageType storeId stateCode zipCode pageContext moduleConfigs adsContext adRequestComposite}fragment SkylineAdDataDisplayAdFragment on AdData{...on DisplayAd{json status}}fragment DynamicAdContainerConfigsFragment on TempoWM_GLASSWWWDynamicAdContainerConfigs{_rawConfigs adModules{moduleType moduleLocation priority adServers{adServer}}zoneLocation lazy}fragment BrandAmplifierAdConfigs on TempoWM_GLASSWWWBrandAmplifierAdConfigs{_rawConfigs moduleLocation ad{...SponsoredBrandsAdFragment}}fragment SponsoredBrandsAdFragment on Ad{...AdFragment adContent{type data{__typename...AdDataSponsoredBrandsFragment}}}fragment AdDataSponsoredBrandsFragment on AdData{...on SponsoredBrands{adUuid adExpInfo moduleInfo brands{logo{featuredHeadline featuredImage featuredImageName featuredUrl logoClickTrackUrl}products{...ProductFragment}}}}fragment ProductFragment on Product{usItemId offerId badges{flags{__typename...on BaseBadge{id text key query type styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought criteria{name value}}}labels{__typename...on BaseBadge{id text key}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{id text key}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType rank slaText styleId text type}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}priceInfo{priceDisplayCodes{rollback reducedPrice eligibleForAssociateDiscount clearance strikethrough submapType priceDisplayCondition unitOfMeasure pricePerUnitUom}currentPrice{price priceString priceDisplay}wasPrice{price priceString}listPrice{price priceString}priceRange{minPrice maxPrice priceString}unitPrice{price priceString}savingsAmount{priceString}comparisonPrice{priceString}subscriptionPrice{priceString subscriptionString price minPrice maxPrice intervalFrequency duration percentageRate durationUOM interestUOM}wPlusEarlyAccessPrice{memberPrice{price priceString priceDisplay}savings{amount priceString}eventStartTime eventStartTimeDisplay}}annualEventV2 earlyAccessEvent isEarlyAccessItem eventAttributes{priceFlip specialBuy}snapEligible showOptions sponsoredProduct{spQs clickBeacon spTags}canonicalUrl numberOfReviews averageRating availabilityStatus imageInfo{thumbnailUrl allImages{id url}}name fulfillmentBadge classType type showAtc p13nData{predictedQuantity flags{PREVIOUSLY_PURCHASED{text}CUSTOMERS_PICK{text}}labels{PREVIOUSLY_PURCHASED{text}CUSTOMERS_PICK{text}}}brand}fragment SearchNonItemFragment on TempoWM_GLASSWWWSearchNonItemConfigs{title subTitle urlLinkText url}fragment HorizontalChipModuleConfigsFragment on TempoWM_GLASSWWWHorizontalChipModuleConfigs{chipModuleSource:moduleSource heading headingColor backgroundImage{src alt}backgroundColor desktopImageHeight desktopImageWidth mobileImageHeight mobileImageWidth chipModule{title url{linkText title clickThrough{type value}}}chipModuleWithImages{title titleColor url{linkText title clickThrough{type value}}image{assetId assetName alt clickThrough{type value}height src title width}}}fragment SkinnyBannerFragment on TempoWM_GLASSWWWSkinnyBannerConfigs{campaignsV1{bannerType desktopBannerHeight bannerImage{src title alt assetId assetName}mobileBannerHeight mobileImage{src title alt assetId assetName}clickThroughUrl{clickThrough{value}}backgroundColor heading{title fontColor}subHeading{title fontColor}bannerCta{ctaLink{linkText clickThrough{value}}textColor ctaType}}}fragment TileTakeOverProductFragment on TempoWM_GLASSWWWTileTakeOverProductConfigs{dwebSlots mwebSlots overrideDefaultTiles TileTakeOverProductDetailsV1{pageNumber span dwebPosition mwebPosition title subtitle image{src alt assetId assetName}logoImage{src alt}backgroundColor titleTextColor subtitleTextColor tileCta{ctaLink{clickThrough{value}linkText title uid}ctaType ctaTextColor}adsEnabled adCardLocation enableLazyLoad}}fragment FashionTopNavFragment on TempoWM_GLASSWWWCategoryTopNavConfigs{navHeaders{header{linkText clickThrough{value}}headerImageGroup{headerImage{alt src assetId assetName}imgTitle imgSubText imgLink{linkText title clickThrough{value}}}categoryGroup{category{linkText clickThrough{value}}startNewColumn subCategoryGroup{subCategory{linkText clickThrough{value}}isBold openInNewTab}}}}fragment RelatedSearch on SearchInterface{relatedSearch{title url imageUrl}}fragment AutoVehicle on AutoVehicle{cid color default documentType fitment{baseBodyType baseVehicleId engineOptions{id isSelected label}smartSubModel tireSizeOptions{diameter isCustom isSelected loadIndex positions ratio speedRating tirePressureFront tirePressureRear tireSize width}trim}isDually licensePlate licensePlateState licensePlateStateCode make model reminders{id}source sourceType subModel{subModelId subModelName}subModelOptions{subModelId subModelName}vehicleId vehicleType vin year}fragment SponsoredVideoAdFragment on TempoWM_GLASSWWWSponsoredVideoAdConfigs{__typename sponsoredVideoAd{ad{adContent{data{...on SponsoredVideos{adUuid hasVideo moduleInfo}}}}}}',
        'variables': {
            'id': '',
            'dealsId': '',
            'query': query,
            'page': 1,
            'prg': 'desktop',
            'catId': '',
            'facet': '',
            'sort': 'best_match',
            'rawFacet': '',
            'seoPath': '',
            'ps': 40,
            'limit': 40,
            'ptss': '',
            'trsp': '',
            'beShelfId': '',
            'recall_set': '',
            'module_search': '',
            'min_price': '',
            'max_price': '',
            'storeSlotBooked': '',
            'additionalQueryParams': {
                'hidden_facet': None,
                'translation': None,
                'isMoreOptionsTileEnabled': True,
            },
            'searchArgs': {
                'query': query,
                'cat_id': '',
                'prg': 'desktop',
                'facet': '',
            },
            'fitmentFieldParams': {
                'powerSportEnabled': True,
                'dynamicFitmentEnabled': True,
                'extendedAttributesEnabled': False,
            },
            'fitmentSearchParams': {
                'id': '',
                'dealsId': '',
                'query': query,
                'page': 1,
                'prg': 'desktop',
                'catId': '',
                'facet': '',
                'sort': 'best_match',
                'rawFacet': '',
                'seoPath': '',
                'ps': 40,
                'limit': 40,
                'ptss': '',
                'trsp': '',
                'beShelfId': '',
                'recall_set': '',
                'module_search': '',
                'min_price': '',
                'max_price': '',
                'storeSlotBooked': '',
                'additionalQueryParams': {
                    'hidden_facet': None,
                    'translation': None,
                    'isMoreOptionsTileEnabled': True,
                },
                'searchArgs': {
                    'query': query,
                    'cat_id': '',
                    'prg': 'desktop',
                    'facet': '',
                },
                'cat_id': '',
                '_be_shelf_id': '',
            },
            'enableFashionTopNav': False,
            'enableRelatedSearches': False,
            'enablePortableFacets': True,
            'enableFacetCount': True,
            'fetchMarquee': True,
            'fetchSkyline': True,
            'fetchGallery': False,
            'fetchSbaTop': True,
            'fetchDac': False,
            'tenant': 'CA_GLASS',
            'enableFlattenedFitment': False,
            'enableMultiSave': True,
            'enableSellerType': True,
            'pageType': 'SearchPage',
        },
    }

    response = requests.post(
        'https://www.walmart.ca/orchestra/graphql/search',
        params=params,
        cookies=cookies,
        headers=headers,
        json=json_data,
    )
    #print(response.text)
    
    soup = BeautifulSoup(response.content, 'html.parser')
    
    #print(soup)

    return response.json()

if __name__ == '__main__':
    fetch_walmartV2('eggs')